# Generated by Django 5.1 on 2024-08-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_category_puzzle_puzzleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='priority',
            field=models.CharField(choices=[('Nowy', 'Nowy'), ('Bardzo dobry', 'Bardzo dobry'), ('Dobry', 'Dobry'), ('Średni', 'Średni'), ('Zły', 'Zły')], default='Bardzo dobry', max_length=12),
        ),
    ]
