# Generated by Django 5.1 on 2024-08-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_priority_puzzle_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzleimage',
            old_name='images',
            new_name='image',
        ),
    ]
