# Generated by Django 5.1 on 2024-08-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_rename_images_puzzleimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/puzzles'),
        ),
        migrations.DeleteModel(
            name='PuzzleImage',
        ),
    ]
