# Generated by Django 5.1 on 2024-08-25 15:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_puzzle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
