# Generated by Django 5.1 on 2024-08-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_puzzle_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='category',
            field=models.ManyToManyField(blank=True, to='website.category'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='image',
            field=models.ImageField(upload_to='uploads/puzzles'),
        ),
    ]
