# Generated by Django 5.1 on 2024-08-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_puzzle_category_alter_puzzle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default="{% static 'images/userimage.png' %}", upload_to='uploads/users'),
        ),
    ]
